/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


/**
 *
 * @author Adminsena
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGestionarMesas = new javax.swing.JButton();
        btnGestionarClientes = new javax.swing.JButton();
        GestionarPedidos = new javax.swing.JButton();
        btnGestionarFacturas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGestionarPlatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 51));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel1.setText("GESTION DE UN RESTAURANTE ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        btnGestionarMesas.setBackground(new java.awt.Color(0, 0, 51));
        btnGestionarMesas.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGestionarMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarMesas.setText("Gestionar Mesas");
        btnGestionarMesas.addActionListener(this::btnGestionarMesasActionPerformed);

        btnGestionarClientes.setBackground(new java.awt.Color(0, 0, 51));
        btnGestionarClientes.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGestionarClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarClientes.setText("Gestionar Clientes");
        btnGestionarClientes.addActionListener(this::btnGestionarClientesActionPerformed);

        GestionarPedidos.setBackground(new java.awt.Color(0, 0, 51));
        GestionarPedidos.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        GestionarPedidos.setForeground(new java.awt.Color(255, 255, 255));
        GestionarPedidos.setText("Gestionar Pedidos ");
        GestionarPedidos.addActionListener(this::GestionarPedidosActionPerformed);

        btnGestionarFacturas.setBackground(new java.awt.Color(0, 0, 51));
        btnGestionarFacturas.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGestionarFacturas.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarFacturas.setText("Gestionar Facturas");
        btnGestionarFacturas.addActionListener(this::btnGestionarFacturasActionPerformed);

        btnSalir.setBackground(new java.awt.Color(255, 51, 0));
        btnSalir.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setAutoscrolls(true);
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        btnGestionarPlatos.setBackground(new java.awt.Color(0, 0, 51));
        btnGestionarPlatos.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnGestionarPlatos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarPlatos.setText("Gestionar Platos");
        btnGestionarPlatos.addActionListener(this::btnGestionarPlatosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GestionarPedidos)
                    .addComponent(btnGestionarMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionarClientes)
                    .addComponent(btnGestionarFacturas))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarPlatos))
                .addGap(80, 92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionarMesas)
                    .addComponent(btnGestionarClientes)
                    .addComponent(btnGestionarPlatos))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GestionarPedidos)
                    .addComponent(btnGestionarFacturas)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarClientesActionPerformed
        VistaCliente ventana = new VistaCliente();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnGestionarClientesActionPerformed

    private void btnGestionarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMesasActionPerformed
      VistaMesa ventana = new VistaMesa();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnGestionarMesasActionPerformed

    private void GestionarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarPedidosActionPerformed
        VistaPedido ventana = new VistaPedido();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_GestionarPedidosActionPerformed

    private void btnGestionarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarFacturasActionPerformed
        VistaFacturas ventana = new VistaFacturas();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnGestionarFacturasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGestionarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPlatosActionPerformed
        VistaPlato ventana = new VistaPlato();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnGestionarPlatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestionarPedidos;
    private javax.swing.JButton btnGestionarClientes;
    private javax.swing.JButton btnGestionarFacturas;
    private javax.swing.JButton btnGestionarMesas;
    private javax.swing.JButton btnGestionarPlatos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}