/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Lenovo
 */
import dao.DetallePedidoDAO;
import modelo.DetallePedido;
import dao.PedidoDAO;
import modelo.Pedido;
import java.util.List;
import dao.FacturaDAO;
import dao.MesaDAO;
import modelo.Factura;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import modelo.Mesa;
public class VistaFacturas extends javax.swing.JFrame {
    private FacturaDAO facturaDAO = new FacturaDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaFacturas.class.getName());

    
    public VistaFacturas() {
        initComponents();
        jftfFecha.addActionListener(evt -> btnGenerarFacturaActionPerformed(evt));
        txtTotal.setEditable(false);
    cargarTabla();
    cargarPedidos();        
    setLocationRelativeTo(null);
    
    }
    private void cargarTabla() {
    
    DefaultTableModel modelo = (DefaultTableModel) tablafacturas.getModel();
    modelo.setRowCount(0);

    
    List<Factura> lista = facturaDAO.listar();

    for (Factura factura : lista) {
        modelo.addRow(new Object[]{
            factura.getIDFactura(),      
            factura.getIDPedido(),
            factura.getFecha()!= null ? factura.getFecha().toString() : "",
            factura.getTotal(),
            factura.getMetodoPago(),


        });
    }
    }
     private void limpiarCampos() {
        cmbPedido.setSelectedIndex(-1);  
        jftfFecha.setText("");                 
    txtTotal.setText("");
         cmbMetodoPago.setSelectedIndex(0);  
}
     private void cargarPedidos() {
    cmbPedido.removeAllItems();
    
    PedidoDAO pedidoDAO = new PedidoDAO();
    List<Pedido> lista = pedidoDAO.listar();
    
    for (Pedido pedido : lista) {
        
        cmbPedido.addItem(pedido.getIDPedido() + " - Estado: " + pedido.getEstado());
    }
}
     private void verificarDetalles(int idPedido) {
    DetallePedidoDAO detalleDAO = new DetallePedidoDAO();
    List<DetallePedido> lista = detalleDAO.listarPorPedido(idPedido);
    
    System.out.println("Detalles encontrados para el pedido " + idPedido + ": " + lista.size());
    
    for (DetallePedido d : lista) {
        System.out.println("Plato: " + d.getIDPlato() + " | Cantidad: " + d.getCantidad() + " | Subtotal: " + d.getSubTotal());
    }
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbPedido = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jftfFecha = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablafacturas = new javax.swing.JTable();
        btnGenerarFactura = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("Pedido");

        cmbPedido.setFont(new java.awt.Font("Nirmala UI Semilight", 3, 14)); // NOI18N
        cmbPedido.addActionListener(this::cmbPedidoActionPerformed);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Fecha");

        jftfFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Total");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Metodo De Pago");

        txtTotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cmbMetodoPago.setFont(new java.awt.Font("Nirmala UI Semilight", 3, 14)); // NOI18N
        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", " ", " " }));
        cmbMetodoPago.addActionListener(this::cmbMetodoPagoActionPerformed);

        tablafacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Factura", "Pedido", "Fecha", "Total", "Metodo de pago"
            }
        ));
        tablafacturas.setGridColor(new java.awt.Color(0, 0, 0));
        tablafacturas.setSelectionBackground(new java.awt.Color(16, 185, 129));
        tablafacturas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tablafacturas);

        btnGenerarFactura.setBackground(new java.awt.Color(16, 185, 129));
        btnGenerarFactura.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnGenerarFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.addActionListener(this::btnGenerarFacturaActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(255, 51, 0));
        btnEliminar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(241, 245, 249));
        btnLimpiar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jLabel5.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel5.setText("Facturas");

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTotal)
                            .addComponent(cmbMetodoPago, 0, 211, Short.MAX_VALUE))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jftfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPedidoActionPerformed
      if (cmbPedido.getSelectedIndex() == -1) {
        txtTotal.setText("");
        return;
    }
    
    try {
        String item = cmbPedido.getSelectedItem().toString();
        int idPedido = Integer.parseInt(item.split(" - ")[0]);
        
        DetallePedidoDAO detalleDAO = new DetallePedidoDAO();
        
        
        List<DetallePedido> lista = detalleDAO.listarPorPedido(idPedido);
        double total = 0;
        
        for (DetallePedido d : lista) {
            total += d.getSubTotal();
        }
        
        txtTotal.setText(String.format("%.2f", total));
        
       
        System.out.println("Pedido ID: " + idPedido + " | Detalles: " + lista.size() + " | Total: " + total);
        
    } catch (Exception e) {
        txtTotal.setText("0.00");
        e.printStackTrace();
    }
    }//GEN-LAST:event_cmbPedidoActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
      if (cmbPedido.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un pedido");
        return;
    }
    
    try {
        Factura factura = new Factura();
        
       
        String item = cmbPedido.getSelectedItem().toString();
        int idPedido = Integer.parseInt(item.split(" - ")[0]);
        factura.setIDPedido(idPedido);
        
        
        factura.setFecha(java.time.LocalDateTime.now());
        
        
        String totalTexto = txtTotal.getText().trim().replace(",", ".");
        double total = Double.parseDouble(totalTexto);
        factura.setTotal(total);
        
       
        factura.setMetodoPago(cmbMetodoPago.getSelectedItem().toString());
        
        if (facturaDAO.agregar(factura)) {
            JOptionPane.showMessageDialog(this, "Factura generada correctamente");
            cargarTabla();
            limpiarCampos();
            cargarPedidos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al generar la factura");
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tablafacturas.getSelectedRow();
    
    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar una factura de la tabla");
        return;
    }
    
    int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de eliminar esta factura?",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
    );
    
    if (confirmacion == JOptionPane.YES_OPTION) {
        int id = Integer.parseInt(tablafacturas.getValueAt(fila, 0).toString());
        
        if (facturaDAO.eliminar(id)) {
            JOptionPane.showMessageDialog(this, "Factura eliminada correctamente");
            cargarTabla();
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al eliminar la factura");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cmbMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodoPagoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed
  private void tablafacturasMouseClicked(java.awt.event.MouseEvent evt) {
    
    int fila = tablafacturas.getSelectedRow();
    
    if (fila >= 0) {
       
        cmbPedido.setSelectedItem(tablafacturas.getValueAt(fila, 1).toString());
        
       
        jftfFecha.setText(tablafacturas.getValueAt(fila, 2).toString());
        
        txtTotal.setText(tablafacturas.getValueAt(fila, 3).toString());
        
       
        cmbMetodoPago.setSelectedItem(tablafacturas.getValueAt(fila, 4).toString());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaFacturas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JComboBox<String> cmbPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jftfFecha;
    private javax.swing.JTable tablafacturas;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
