/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Lenovo
 */
import dao.PedidoDAO;
import dao.DetallePedidoDAO;
import dao.MesaDAO;
import dao.ClienteDAO;
import dao.PlatoDAO;
import modelo.Pedido;
import modelo.DetallePedido;
import modelo.Mesa;
import modelo.Cliente;
import modelo.Plato;
import java.util.List;
import java.time.LocalDateTime;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
public class VistaPedido extends javax.swing.JFrame {
    private PedidoDAO pedidoDAO = new PedidoDAO();
private DetallePedidoDAO detalleDAO = new DetallePedidoDAO();
private MesaDAO mesaDAO = new MesaDAO();
private ClienteDAO clienteDAO = new ClienteDAO();
private PlatoDAO platoDAO = new PlatoDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPedido.class.getName());

    /**
     * Creates new form VistaPedido
     */
    public VistaPedido() {
        initComponents();
        txtCantidad.addActionListener(evt -> btnGuardarPedidoActionPerformed(evt));
        cargarCombos();          
    setLocationRelativeTo(null);
    }
    private void cargarCombos() {
    
    
    cmbMesa.removeAllItems();
    List<Mesa> mesas = mesaDAO.listar();
    for (Mesa mesa : mesas) {
        cmbMesa.addItem(mesa.getIDMesa() + " - Mesa " + mesa.getNumero());
    }
    
    
    cmbCliente.removeAllItems();
    List<Cliente> clientes = clienteDAO.listar();
    for (Cliente cliente : clientes) {
        cmbCliente.addItem(cliente.getIDCliente() + " - " + cliente.getNombre());
    }
    
    
    cmbPlatos.removeAllItems();
    List<Plato> platos = platoDAO.listar();
    for (Plato plato : platos) {
        cmbPlatos.addItem(plato.getIDPlato() + " - " + plato.getNombre() + " ($" + plato.getPrecio() + ")");
    }
    
    
    cmbEstado.removeAllItems();
    cmbEstado.addItem("Pendiente");
    cmbEstado.addItem("Servido");
    cmbEstado.addItem("Pagado");
}
    private void limpiarDetalle() {
    cmbPlatos.setSelectedIndex(-1);
    txtCantidad.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbMesa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbPlatos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladetalles = new javax.swing.JTable();
        btnGuardarPedido = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregarPlato = new javax.swing.JButton();
        btnEliminarPlato = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("Mesa");

        cmbMesa.setFont(new java.awt.Font("Nirmala UI Semilight", 3, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Cliente");

        cmbCliente.setFont(new java.awt.Font("Nirmala UI Semilight", 3, 14)); // NOI18N
        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Estado");

        cmbEstado.setFont(new java.awt.Font("Nirmala UI Semilight", 3, 14)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Servido", "Pagado", " " }));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Platos");

        cmbPlatos.setFont(new java.awt.Font("Nirmala UI Semilight", 3, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad");

        txtCantidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tabladetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Plato", "Cantidad", "SubTotal"
            }
        ));
        tabladetalles.setGridColor(new java.awt.Color(0, 0, 0));
        tabladetalles.setSelectionBackground(new java.awt.Color(16, 185, 129));
        tabladetalles.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabladetalles);

        btnGuardarPedido.setBackground(new java.awt.Color(16, 185, 129));
        btnGuardarPedido.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnGuardarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPedido.setText("Guardar Pedido");
        btnGuardarPedido.addActionListener(this::btnGuardarPedidoActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(255, 51, 0));
        btnCancelar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnAgregarPlato.setBackground(new java.awt.Color(241, 245, 249));
        btnAgregarPlato.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAgregarPlato.setText("Agregar Plato Al Pedido");
        btnAgregarPlato.addActionListener(this::btnAgregarPlatoActionPerformed);

        btnEliminarPlato.setBackground(new java.awt.Color(255, 51, 0));
        btnEliminarPlato.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnEliminarPlato.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPlato.setText("Eliminar Plato");
        btnEliminarPlato.addActionListener(this::btnEliminarPlatoActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(241, 245, 249));
        btnLimpiar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        jLabel6.setFont(new java.awt.Font("Haettenschweiler", 0, 48)); // NOI18N
        jLabel6.setText("Pedidos");

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addComponent(btnGuardarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnEliminarPlato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarPlato)))
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(285, 285, 285))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnRegresar)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnGuardarPedido))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarPlato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEliminarPlato, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlatoActionPerformed
       
        
        if (cmbPlatos.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un plato");
        return;
    }
    
    if (txtCantidad.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debes ingresar la cantidad");
        return;
    }
    
    try {
        int cantidad = Integer.parseInt(txtCantidad.getText().trim());
        
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0");
            return;
        }
        
        // Formato del combo: "1 - Suchi ($30000.0)"
        String itemPlato = cmbPlatos.getSelectedItem().toString();
        String[] partes = itemPlato.split(" - ");
        int idPlato = Integer.parseInt(partes[0]);
        
        String nombrePlato = partes[1].split(" \\(")[0]; // "Suchi"
        
        // Buscar el precio
        double precio = 0;
        List<Plato> platos = platoDAO.listar();
        for (Plato p : platos) {
            if (p.getIDPlato() == idPlato) {
                precio = p.getPrecio();
                break;
            }
        }
        
        double subtotal = cantidad * precio;
        
        // Agregar a la tabla (3 columnas: Plato, Cantidad, SubTotal)
        DefaultTableModel modelo = (DefaultTableModel) tabladetalles.getModel();
        modelo.addRow(new Object[]{
            idPlato + " - " + nombrePlato,  // Columna 0: Plato (guardamos ID + nombre)
            cantidad,                       // Columna 1: Cantidad
            subtotal                        // Columna 2: SubTotal
        });
        
        limpiarDetalle();
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "La cantidad debe ser un número válido");
    }
    }//GEN-LAST:event_btnAgregarPlatoActionPerformed

    private void btnEliminarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlatoActionPerformed
        int fila = tabladetalles.getSelectedRow(); // ajusta el nombre de tu tabla
    
    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un plato de la tabla");
        return;
    }
    
    DefaultTableModel modelo = (DefaultTableModel) tabladetalles.getModel();
    modelo.removeRow(fila);
    }//GEN-LAST:event_btnEliminarPlatoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cmbMesa.setSelectedIndex(-1);
    cmbCliente.setSelectedIndex(-1);
    cmbEstado.setSelectedIndex(0);
    
   
    DefaultTableModel modelo = (DefaultTableModel) tabladetalles.getModel();
    modelo.setRowCount(0);
    
    limpiarDetalle();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPedidoActionPerformed
if (cmbMesa.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar una mesa");
        return;
    }
    
    if (cmbCliente.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(this, "Debes seleccionar un cliente");
        return;
    }
    
    DefaultTableModel modelo = (DefaultTableModel) tabladetalles.getModel();
    
    if (modelo.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Debes agregar al menos un plato");
        return;
    }
    
    try {
        // ===== 1. Guardar cabecera =====
        Pedido pedido = new Pedido();
        
        String itemMesa = cmbMesa.getSelectedItem().toString();
        int idMesa = Integer.parseInt(itemMesa.split(" - ")[0]);
        
        String itemCliente = cmbCliente.getSelectedItem().toString();
        int idCliente = Integer.parseInt(itemCliente.split(" - ")[0]);
        
        pedido.setIDMesa(idMesa);
        pedido.setIDCliente(idCliente);
        pedido.setFecha(LocalDateTime.now());
        pedido.setEstado(cmbEstado.getSelectedItem().toString());
        
        int idPedidoGenerado = pedidoDAO.agregar(pedido);
        
        if (idPedidoGenerado == -1) {
            JOptionPane.showMessageDialog(this, "Error al guardar el pedido");
            return;
        }
        
        // ===== 2. Guardar detalles =====
        for (int i = 0; i < modelo.getRowCount(); i++) {
            
            Object valor = modelo.getValueAt(i, 0);
            if (valor == null || valor.toString().trim().isEmpty()) {
                continue;
            }
            
            // Columna 0 tiene "1 - Suchi"
            String platoTexto = modelo.getValueAt(i, 0).toString();
            int idPlato = Integer.parseInt(platoTexto.split(" - ")[0]);
            
            int cantidad = Integer.parseInt(modelo.getValueAt(i, 1).toString());
            double subtotal = Double.parseDouble(modelo.getValueAt(i, 2).toString());
            
            DetallePedido detalle = new DetallePedido();
            detalle.setIDPedido(idPedidoGenerado);
            detalle.setIDPlato(idPlato);
            detalle.setCantidad(cantidad);
            detalle.setSubTotal(subtotal);
            
            detalleDAO.agregar(detalle);
        }
        
        JOptionPane.showMessageDialog(this, "Pedido guardado correctamente. ID: " + idPedidoGenerado);
        btnLimpiarActionPerformed(null);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el pedido: " + e.getMessage());
        e.printStackTrace();
    }       
    }//GEN-LAST:event_btnGuardarPedidoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed
private double calcularTotal() {
    DefaultTableModel modelo = (DefaultTableModel) tabladetalles.getModel();
    double total = 0;
    
    for (int i = 0; i < modelo.getRowCount(); i++) {
        total += Double.parseDouble(modelo.getValueAt(i, 3).toString());
    }
    
    return total;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPlato;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarPlato;
    private javax.swing.JButton btnGuardarPedido;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbMesa;
    private javax.swing.JComboBox<String> cmbPlatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladetalles;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
