/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Adminsena
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGestionarMesas = new javax.swing.JButton();
        btnGestionarClientes = new javax.swing.JButton();
        btnGestionarPlatos = new javax.swing.JButton();
        GestionarPedidos = new javax.swing.JButton();
        btnGestionarFacturas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GESTION DE UN RESTAURANTE ");

        btnGestionarMesas.setText("Gestionar Mesas");
        btnGestionarMesas.addActionListener(this::btnGestionarMesasActionPerformed);

        btnGestionarClientes.setText("Gestionar Clientes");
        btnGestionarClientes.addActionListener(this::btnGestionarClientesActionPerformed);

        btnGestionarPlatos.setText("Gestionar Platos");
        btnGestionarPlatos.addActionListener(this::btnGestionarPlatosActionPerformed);

        GestionarPedidos.setText("Gestionar Pedidos ");
        GestionarPedidos.addActionListener(this::GestionarPedidosActionPerformed);

        btnGestionarFacturas.setText("Gestionar Facturas");
        btnGestionarFacturas.addActionListener(this::btnGestionarFacturasActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GestionarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGestionarMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestionarClientes)
                            .addComponent(btnGestionarFacturas)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionarPlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGestionarMesas)
                    .addComponent(btnGestionarClientes)
                    .addComponent(btnGestionarPlatos))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GestionarPedidos)
                    .addComponent(btnGestionarFacturas)
                    .addComponent(btnSalir))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarClientesActionPerformed
        VistaCliente ventana = new VistaCliente();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnGestionarClientesActionPerformed

    private void btnGestionarMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMesasActionPerformed
      VistaMesa ventana = new VistaMesa();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnGestionarMesasActionPerformed

    private void btnGestionarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPlatosActionPerformed
     VistaPlato ventana = new VistaPlato();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnGestionarPlatosActionPerformed

    private void GestionarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionarPedidosActionPerformed
        VistaPedido ventana = new VistaPedido();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_GestionarPedidosActionPerformed

    private void btnGestionarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarFacturasActionPerformed
        VistaFacturas ventana = new VistaFacturas();
ventana.setVisible(true);
ventana.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btnGestionarFacturasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GestionarPedidos;
    private javax.swing.JButton btnGestionarClientes;
    private javax.swing.JButton btnGestionarFacturas;
    private javax.swing.JButton btnGestionarMesas;
    private javax.swing.JButton btnGestionarPlatos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
